const REGISTER = "REGISTER";
const LOGIN = "LOGIN";
const REGISTER_HOSPITAL = "REGISTER_HOSPITAL";
const LOGOUT = "LOGOUT";
const CHILD_REGISTRATION = "CHILD_REGISTRATION";

module.exports = {
  REGISTER,
  LOGIN,
  REGISTER_HOSPITAL,
  LOGOUT,
  CHILD_REGISTRATION,
};
